# Generated by Django 5.2.6 on 2025-10-06 07:18

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEstudiante', '0003_remove_estudiante_id_estudiante_id_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Silabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sílabo', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silabos', to='AppEstudiante.materia')),
                ('id_Paralelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silabos', to='AppEstudiante.paralelo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='silabos', to='AppEstudiante.periodoacademico')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('semana', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('id_Silabo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='AppEstudiante.silabo')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('id_Tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='AppEstudiante.tema')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='silabo',
            constraint=models.UniqueConstraint(condition=models.Q(('id_Paralelo__isnull', True)), fields=('id_Materia', 'periodo'), name='uniq_silabo_materia_periodo'),
        ),
        migrations.AddConstraint(
            model_name='silabo',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('id_Materia', 'periodo', 'id_Paralelo'), name='uniq_silabo_materia_periodo_paralelo'),
        ),
        migrations.AddConstraint(
            model_name='tema',
            constraint=models.UniqueConstraint(fields=('id_Silabo', 'orden'), name='uniq_tema_orden_por_silabo'),
        ),
        migrations.AddConstraint(
            model_name='subtema',
            constraint=models.UniqueConstraint(fields=('id_Tema', 'orden'), name='uniq_subtema_orden_por_tema'),
        ),
    ]
